repos:
-   repo: https://github.com/dapperfu/pre-commit-hooks-matlab
    rev: 2023.09.010
    hooks:
    -   id: commitHook
    -   id: close_simulink_subsystems
    -   id: matlab_smart_indent
        args: ['--files', 'all']